language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 7.2
          env: statictests=disallow
        - php: 7.3
          env: statictests=disallow
        - php: 7.4
          env: statictests=allow
        - php: 8.0
          env: statictests=allow
    fast_finish: true

before_install:
    - composer self-update --preview

install:
    - composer install --no-progress --optimize-autoloader

script:
    - ./vendor/bin/phpcs
    - if [ "$statictests" = "allow" ]; then ./vendor/bin/phpstan analyse; fi;
    - if [ "$statictests" = "allow" ]; then ./vendor/bin/psalm; fi;
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash) -f coverage.xml
