name: Tests
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        php: ['7.2', '7.3', '7.4']
        ignore-versions: ['']
        include:
            - php: '8.0'
              ignore-versions: '--ignore-platform-reqs'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, curl
          coverage: xdebug
          tools: composer:v2

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer update ${{ matrix.ignore-versions }} --no-progress --optimize-autoloader

      - name: Check Coding Standard
        run: vendor/bin/phpcs

      - name: Test with Phpunit
        run: |
          vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
          bash <(curl -s https://codecov.io/bash) -f coverage.clover

      - name: Test with Phpstan
        run: vendor/bin/phpstan analyse

      - name: Test with Psalm
        run: vendor/bin/psalm
